(() => {
  const q = (s, r=document) => r.querySelector(s);
  const qa = (s, r=document) => [...r.querySelectorAll(s)];
  const num = v => Number(v) || 0;
  const clamp2 = (v,min,max) => Math.max(min,Math.min(max,v));
  const normalizeAirport = v => String(v||"").trim().toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,8);

  const DESTINATION_AIRPORTS = {
    wdw:{code:"MCO",label:"Orlando International"}, dlr:{code:"SNA",label:"John Wayne / Anaheim"}, tokyo:{code:"HND",label:"Tokyo Haneda"}, paris:{code:"CDG",label:"Paris Charles de Gaulle"}, hk:{code:"HKG",label:"Hong Kong International"}, shanghai:{code:"PVG",label:"Shanghai Pudong"}, aulani:{code:"HNL",label:"Honolulu International"}, cruise:{code:"",label:"Cruise port varies by sailing"}
  };

  const HOTELS = {
    wdw:[{id:"pop",type:"on",name:"Disney’s Pop Century Resort",tier:"Value",budget:220},{id:"pofq",type:"on",name:"Disney’s Port Orleans Resort – French Quarter",tier:"Moderate",budget:360},{id:"wilderness",type:"on",name:"Disney’s Wilderness Lodge",tier:"Deluxe",budget:620},{id:"drury",type:"off",name:"Drury Plaza Hotel Orlando – Disney Springs Area",tier:"Off-property value",budget:190},{id:"wyndham",type:"off",name:"Wyndham Garden Lake Buena Vista",tier:"Disney Springs area",budget:220},{id:"jwbc",type:"off",name:"JW Marriott Orlando Bonnet Creek",tier:"Off-property premium",budget:430}],
    dlr:[{id:"pixar",type:"on",name:"Pixar Place Hotel",tier:"Disney hotel",budget:480},{id:"dlhotel",type:"on",name:"Disneyland Hotel",tier:"Disney hotel",budget:680},{id:"grandcal",type:"on",name:"Disney’s Grand Californian Hotel & Spa",tier:"Disney premium",budget:850},{id:"hyatthouse",type:"off",name:"Hyatt House at Anaheim Resort",tier:"Walkable off-property",budget:270},{id:"courtyard",type:"off",name:"Courtyard Anaheim Theme Park Entrance",tier:"Walkable family option",budget:350},{id:"westin",type:"off",name:"The Westin Anaheim Resort",tier:"Off-property premium",budget:330}],
    tokyo:[{id:"celebration",type:"on",name:"Tokyo Disney Celebration Hotel",tier:"Disney value",budget:26000},{id:"ambassador",type:"on",name:"Disney Ambassador Hotel",tier:"Disney hotel",budget:52000},{id:"fantasy",type:"on",name:"Tokyo DisneySea Fantasy Springs Hotel",tier:"Disney premium",budget:90000},{id:"hiltonbay",type:"off",name:"Hilton Tokyo Bay",tier:"Official hotel area",budget:30000},{id:"sheratonbay",type:"off",name:"Sheraton Grande Tokyo Bay Hotel",tier:"Official hotel area",budget:32000}],
    paris:[{id:"cheyenne",type:"on",name:"Disney Hotel Cheyenne",tier:"Disney value",budget:260},{id:"sequoia",type:"on",name:"Disney Sequoia Lodge",tier:"Disney moderate",budget:390},{id:"dlandhotel",type:"on",name:"Disneyland Hotel",tier:"Disney premium",budget:900},{id:"moxy",type:"off",name:"Moxy Paris Val d’Europe",tier:"Off-property",budget:180},{id:"staycity",type:"off",name:"Staycity Aparthotels Paris Marne La Vallée",tier:"Family off-property",budget:190}],
    hk:[{id:"hollywoodhk",type:"on",name:"Disney’s Hollywood Hotel",tier:"Disney hotel",budget:2200},{id:"explorers",type:"on",name:"Disney Explorers Lodge",tier:"Disney hotel",budget:2600},{id:"hkdhotel",type:"on",name:"Hong Kong Disneyland Hotel",tier:"Disney premium",budget:3300},{id:"novotelcitygate",type:"off",name:"Novotel Citygate Hong Kong",tier:"Airport / transit option",budget:1500}],
    shanghai:[{id:"toystory",type:"on",name:"Toy Story Hotel",tier:"Disney hotel",budget:1700},{id:"shdhotel",type:"on",name:"Shanghai Disneyland Hotel",tier:"Disney premium",budget:3200},{id:"courtyardsh",type:"off",name:"Courtyard by Marriott Shanghai International Tourism and Resorts Zone",tier:"Off-property",budget:850}],
    aulani:[{id:"aulani",type:"on",name:"Aulani, A Disney Resort & Spa",tier:"Disney resort",budget:700},{id:"marriottko",type:"off",name:"Marriott’s Ko Olina Beach Club",tier:"Nearby resort",budget:650},{id:"fsoahu",type:"off",name:"Four Seasons Resort O‘ahu at Ko Olina",tier:"Nearby premium",budget:1200}],
    cruise:[{id:"cruisefare",type:"on",name:"Disney Cruise Line stateroom / package",tier:"Live sailing quote",budget:0},{id:"prepost",type:"off",name:"Pre/post-cruise hotel",tier:"Add a live room quote",budget:250}]
  };

  function childAges(){return qa('[data-child-age]').map(el=>num(el.value));}
  function syncChildren(){
    const count=clamp2(num(q('#children')?.value),0,8),shell=q('#child-ages-shell'),grid=q('#child-age-grid'); if(!shell||!grid)return;
    const existing=childAges(); if(!count){shell.hidden=true;grid.innerHTML='';return} shell.hidden=false;grid.innerHTML='';
    for(let i=0;i<count;i++){const age=existing[i]??7;grid.insertAdjacentHTML('beforeend',`<label class="child-age-field">Child ${i+1}<input data-child-age name="childAge${i+1}" type="number" min="0" max="17" value="${age}" aria-label="Child ${i+1} age at travel"></label>`)}
    syncChildRule();
  }
  function syncChildRule(){const el=q('#child-age-rule');if(!el||!pricing)return;el.textContent=pricing.destinations[q('#destination').value]?.ageNote||'Age rules vary by destination.'}
  function groups(key,adults,ages){const g={adult:num(adults),junior:0,child:0,free:0};ages.forEach(age=>{if(key==='tokyo'){if(age<=3)g.free++;else if(age<=11)g.child++;else if(age<=17)g.junior++;else g.adult++}else if(['wdw','dlr'].includes(key)){if(age<=2)g.free++;else if(age<=9)g.child++;else g.adult++}else if(['paris','hk'].includes(key)){if(age<=2)g.free++;else if(age<=11)g.child++;else g.adult++}else g.child++});g.ticketed=g.adult+g.junior+g.child;return g}

  function ticketCost(d,data,ages){
    const days=num(data.parkDays),g=groups(d.key,data.adults,ages); if(days===0||['aulani','cruise'].includes(d.key))return{total:0,confidence:'live',groups:g,message:d.key==='cruise'?'Cruise fare needs a live sailing quote.':'No theme-park ticket is included for this destination.'};
    if(d.ticketModel==='starting'){if(d.key==='wdw'&&data.ticketStyle==='best'&&days===4){const offer=d.offers.find(o=>o.title.includes('4-Park Magic'));if(offer&&data.startDate<=offer.validThrough)return{total:offer.price*g.ticketed,confidence:'estimate',groups:g,message:`Uses the published adult 4-Park Magic starting price for ${g.ticketed} ticketed guest(s). ${g.free?g.free+' child(ren) age 2 and under excluded. ':''}Verify child pricing, tax and availability live.`}}return{total:d.adultOneDayFrom*g.ticketed*days,confidence:'estimate',groups:g,message:`Uses the published adult starting price of ${money(d.adultOneDayFrom,d.currency)} per day for ${g.ticketed} ticketed guest(s). Actual child pricing, date, park and tax can change the total.`}}
    if(d.ticketModel==='multiday_exact'){const k=String(clamp2(days,2,5)),table=data.ticketStyle==='hopper'?d.hopper:d.multiDay;if(days>=2&&days<=5){const p=table[k];return{total:p.adult*g.adult+p.child*g.child,confidence:'verified',groups:g,message:`Uses Disney's published ${days}-day ${data.ticketStyle==='hopper'?'Park Hopper':'1 Park Per Day'} table with age-based child classification. ${g.free?g.free+' child(ren) age 2 and under excluded.':''}`}}return{total:0,confidence:'live',groups:g,message:'Disneyland publishes 1-day tickets by date tier. Use the official link for a live 1-day quote.'}}
    if(d.ticketModel==='date_exact_adult'){let adultTotal=0,exact=0;for(let i=0;i<days;i++){const dt=new Date(data.startDate+'T12:00:00');dt.setDate(dt.getDate()+i);const p=d.datePricesAdult[dt.toISOString().slice(0,10)];if(p){adultTotal+=p*g.adult;exact++}else adultTotal+=d.adultOneDayFrom*g.adult}const total=adultTotal+(d.juniorOneDayFrom||d.adultOneDayFrom)*g.junior*days+(d.childOneDayFrom||d.adultOneDayFrom)*g.child*days;return{total,confidence:exact===days&&g.junior===0&&g.child===0?'dated':'estimate',groups:g,message:`Adult pricing uses ${exact}/${days} published date-specific day(s); junior and child tickets use published starting fares. Age 3 and under are excluded.`}}
    if(d.ticketModel==='tiered'){if(days===2&&data.ticketStyle==='best'){const o=d.offers.find(x=>x.title.includes('2-Day Fun')),childBase=d.twoDay?.child||849;return{total:o.price*g.adult+childBase*g.child,confidence:'estimate',groups:g,message:'Uses the current 2-Day Fun adult starting fare and a published child two-day value as a planning estimate; verify the live tier.'}}const t=d.tiers[2];return{total:(t.adult*g.adult+t.child*g.child)*days,confidence:'estimate',groups:g,message:'Uses Tier 2 as a working estimate with age-based child classification. Verify the live tier calendar.'}}
    if(d.ticketModel==='range'){const mid=(d.adultOneDayMin+d.adultOneDayMax)/2;return{total:mid*g.ticketed*days,confidence:'estimate',groups:g,message:`Uses the midpoint of Shanghai's published RMB ${d.adultOneDayMin}–${d.adultOneDayMax} adult range. Child/special pricing and exact date require a live check.`}}
    return{total:0,confidence:'live',groups:g,message:'This destination uses dynamic pricing. Open the official source for a live quote.'}
  }

  function syncHotels(){const key=q('#destination')?.value,stay=q('#stay-type')?.value||'on',sel=q('#hotel-candidate'),note=q('#hotel-note');if(!sel)return;const prev=sel.value,all=HOTELS[key]||[],list=['split','manual'].includes(stay)?all:all.filter(h=>h.type===stay);sel.innerHTML='<option value="manual">Use my own lodging budget</option>'+list.map(h=>`<option value="${h.id}">${h.name} · ${h.tier}</option>`).join('');if(list.some(h=>h.id===prev))sel.value=prev;if(note)note.textContent=list.length?'Choose a hotel to seed a planning budget, then replace it with a live room quote when ready.':'Use your own lodging estimate for this trip.'}
  function selectedHotel(){const key=q('#destination')?.value,id=q('#hotel-candidate')?.value;return(HOTELS[key]||[]).find(h=>h.id===id)||null}
  function applyHotel(){const h=selectedHotel(),d=pricing?.destinations[q('#destination').value];if(!h||!d)return;if(h.budget>0)q('#lodging-night').value=h.budget;q('#hotel-note').textContent=`${h.name}: ${money(h.budget,d.currency)} / night is a planning anchor, not a live room rate.`}
  function syncDining(){if(!pricing)return;const d=pricing.destinations[q('#destination').value],base=d.planningDefaults?.foodDaily||0,m={quick:.75,mixed:1,table:1.35,character:1.65}[q('#dining-style')?.value]||1;q('#food-daily').value=Math.round(base*m)}
  function syncTransfer(){if(!pricing)return;const d=pricing.destinations[q('#destination').value],style=q('#transfer-style')?.value||'rideshare';if(style==='manual')return;const m={resort:.55,rideshare:1,rental:1.55,private:2.1}[style]||1;q('#transport-total').value=Math.round((d.planningDefaults?.transportTotal||0)*m)}
  function syncPremium(){if(!pricing)return;const key=q('#destination').value,d=pricing.destinations[key],defs={USD:35,JPY:4500,EUR:35,HKD:280,CNY:220};q('#premium-daily').value=defs[d.currency]||35;q('#premium-days').value=['aulani','cruise'].includes(key)?0:Math.min(2,num(q('#park-days')?.value)||2);qa('[data-premium-symbol]').forEach(s=>s.textContent=d.symbol)}
  function flightLink(){const origin=normalizeAirport(q('#origin-airport')?.value),key=q('#destination')?.value,dest=DESTINATION_AIRPORTS[key],start=q('#start-date')?.value,end=q('#end-date')?.value,pref=q('#flight-preference')?.value||'balanced',link=q('#flight-search-link'),note=q('#route-note');if(!dest||!link)return;const prefText={nonstop:'nonstop flights',value:'lowest practical fare',comfort:'best schedule and comfort',balanced:'best overall route'}[pref];const text=origin&&dest.code?`Flights from ${origin} to ${dest.code} ${start?'departing '+start:''} ${end?'returning '+end:''} ${prefText}`:`Flights to ${dest.label} ${start||''} ${end||''}`;link.href=`https://www.google.com/travel/flights?q=${encodeURIComponent(text)}`;if(note)note.textContent=origin&&dest.code?`Route target: ${origin} → ${dest.code} (${dest.label}).`:`Destination airport: ${dest.label}. Add an origin airport to build the route.`}

  function enhancedBrief(t){const airport=DESTINATION_AIRPORTS[t.d.key];return[`JORDAN — DISNEY TRIP DESIGN`,'',`Destination: ${t.d.name} (${t.d.location})`,`Dates: ${t.startDate} → ${t.endDate} (${t.nights} nights)`,`Flight route: ${t.originAirport||'Origin not set'} → ${airport?.code||airport?.label||'destination'}`,`Flight preference: ${t.flightPreference}`,`Travelers: ${t.adults} adult(s), ${t.childAges.length} child(ren)${t.childAges.length?' · ages '+t.childAges.join(', '):''}`,`Stay style: ${t.stayType}`,`Hotel candidate: ${t.hotel?.name||'Not selected'}`,`Dining style: ${t.diningStyle}`,`Transfer style: ${t.transferStyle}`,`Experience days: ${t.parkDays}`,`Ticket style: ${t.ticketStyle}`,`Paid priority / premium days: ${t.premiumDays}`,'',`WORKING BUDGET (${t.d.currency})`,`Tickets/experiences: ${t.ticket.total?money(t.ticket.total,t.d.currency):'Live quote needed'}`,`Lodging: ${money(t.lodging,t.d.currency)}`,`Airfare: ${money(t.airfare,t.d.currency)}`,`Food + extras: ${money(t.food,t.d.currency)}`,`Ground transport: ${money(t.ground,t.d.currency)}`,`Paid priority / premium: ${money(t.premium,t.d.currency)}`,`Estimated total: ${money(t.total,t.d.currency)}`,'',`Ticket note: ${t.ticket.message}`,`Pricing snapshot checked: ${pricing.updatedAt}`,`Official source: ${t.d.sourceUrl}`].join('\n')}

  function calculateEnhanced(event){event.preventDefault();event.stopImmediatePropagation();if(!pricing)return;const form=q('#trip-builder');if(!form.reportValidity())return;const data=Object.fromEntries(new FormData(form)),ages=childAges();if(num(data.children)!==ages.length){showToast('Add an age for each child.');return}data.originAirport=normalizeAirport(data.originAirport);const d={...pricing.destinations[data.destination],key:data.destination},nights=daysBetween(data.startDate,data.endDate);if(nights<1){showToast('Departure must be after arrival.');return}const people=num(data.adults)+ages.length,ticket=ticketCost(d,data,ages),ticketed=ticket.groups?.ticketed||people,lodging=num(data.lodgingNight)*nights,airfare=num(data.airfarePerson)*people,food=num(data.foodDaily)*people*(nights+1),ground=num(data.transportTotal),premium=num(data.premiumDaily)*num(data.premiumDays)*ticketed,total=ticket.total+lodging+airfare+food+ground+premium;lastTrip={...data,childAges:ages,nights,people,d,ticket,lodging,airfare,food,ground,premium,total,hotel:selectedHotel()};q('#budget-destination').textContent=d.name;q('#grand-total').textContent=money(total,d.currency);q('#ticket-total').textContent=ticket.total?money(ticket.total,d.currency):'Live quote';q('#lodging-total').textContent=money(lodging,d.currency);q('#airfare-total').textContent=money(airfare,d.currency);q('#food-total').textContent=money(food,d.currency);q('#transport-total-display').textContent=money(ground,d.currency);q('#premium-total').textContent=money(premium,d.currency);q('#total-note').textContent=`${nights} nights · ${people} travelers · ${data.parkDays} experience days`;q('#budget-message').textContent=ticket.message;q('#budget-confidence').textContent=ticket.confidence==='verified'?'Strong ticket data':ticket.confidence==='dated'?'Date-specific ticket data':'Mixed live + estimates';q('#official-rate-link').href=d.sourceUrl;const offers=(d.offers||[]).filter(o=>!o.validThrough||data.startDate<=o.validThrough).slice(0,2);q('#matched-offers').innerHTML=offers.map(o=>`<div class="match-offer"><strong>Worth checking: ${o.title}</strong>${o.detail}${o.validThrough?` · valid dates through ${o.validThrough}`:''}</div>`).join('');flightLink();burstFromElement(q('#grand-total'))}

  function syncDestinationEnhancements(){if(!pricing)return;syncChildRule();syncHotels();syncDining();syncTransfer();syncPremium();flightLink()}
  function initSigned(){const overlay=q('#signed-overlay');if(!overlay)return;const triggers=['signed-budget-trigger','about-sign-trigger'].map(id=>document.getElementById(id)).filter(Boolean),replay=q('#signed-replay');let lastTrigger=null;function animate(){overlay.classList.remove('is-active');void overlay.offsetWidth;overlay.classList.add('is-active');sparkleBurst(innerWidth*.5,Math.min(innerHeight*.48,340),18);firework(innerWidth*.5,Math.min(innerHeight*.46,320))}function open(source){if(source?.id==='signed-budget-trigger'&&!lastTrip){showToast('Calculate the trip first, then give it Jordan’s final flourish.');return}lastTrigger=source;const copy=overlay.querySelector('.signed-overlay-copy');copy.textContent=source?.id==='signed-budget-trigger'&&lastTrip?`${lastTrip.d.name} is looking magical. ${money(lastTrip.total,lastTrip.d.currency)} is the current working total — ready for Jordan’s final flourish.`:'A little final flourish for the trips, ideas, and recommendations that feel truly ready.';overlay.hidden=false;overlay.setAttribute('aria-hidden','false');document.body.classList.add('signed-overlay-open');animate();requestAnimationFrame(()=>overlay.querySelector('.signed-overlay-close')?.focus())}function close(){overlay.hidden=true;overlay.setAttribute('aria-hidden','true');overlay.classList.remove('is-active');document.body.classList.remove('signed-overlay-open');lastTrigger?.focus?.()}triggers.forEach(b=>b.addEventListener('click',()=>open(b)));overlay.querySelectorAll('[data-signed-close]').forEach(n=>n.addEventListener('click',close));replay?.addEventListener('click',animate);document.addEventListener('keydown',e=>{if(!overlay.hidden&&e.key==='Escape')close()})}

  function wire(){
    const form=q('#trip-builder');form?.addEventListener('submit',calculateEnhanced,true);
    q('#children')?.addEventListener('input',syncChildren);q('#destination')?.addEventListener('change',()=>setTimeout(syncDestinationEnhancements,0));q('#stay-type')?.addEventListener('change',syncHotels);q('#hotel-candidate')?.addEventListener('change',applyHotel);q('#dining-style')?.addEventListener('change',syncDining);q('#transfer-style')?.addEventListener('change',syncTransfer);q('#origin-airport')?.addEventListener('input',e=>{e.target.value=normalizeAirport(e.target.value);flightLink()});q('#flight-preference')?.addEventListener('change',flightLink);q('#start-date')?.addEventListener('change',flightLink);q('#end-date')?.addEventListener('change',flightLink);q('#park-days')?.addEventListener('change',()=>{const p=q('#premium-days');if(p&&num(p.value)>num(q('#park-days').value))p.value=q('#park-days').value});
    q('#copy-trip')?.addEventListener('click',async e=>{if(!lastTrip?.childAges)return;e.preventDefault();e.stopImmediatePropagation();try{await navigator.clipboard.writeText(enhancedBrief(lastTrip));showToast('Trip brief copied.')}catch{showToast('Copy blocked by browser.')}},true);
    q('#reset-builder')?.addEventListener('click',()=>setTimeout(()=>{syncChildren();syncDestinationEnhancements();q('#premium-total').textContent='—'},0));
    initSigned();
  }
  function waitForPricing(tries=0){if(typeof pricing!=='undefined'&&pricing){syncChildren();syncDestinationEnhancements();return}if(tries<50)setTimeout(()=>waitForPricing(tries+1),100)}
  wire();waitForPricing();
})();